// Typed access to the authored heritage layer.
//
// heritage-places.json is generated by scripts/build-heritage-places.py —
// areas and walks with prose and resolved stops, no route geometry (the map
// client fetches /heritage-walk-geometry.json separately so the polylines
// never enter the server bundle). photos.json is the attribution manifest
// from scripts/fetch-heritage-photos.py; a photo without an entry there has
// no licence on record and must not render.

import places from "./heritage-places.json";
import photoManifest from "../../public/heritage/photos.json";

export type Monument = {
  fad: string;
  name: string;
  registered: boolean;
  lat?: number;
  lon?: number;
};

export type Area = {
  slug: string;
  name: string;
  thai: string;
  district: string;
  tagline: string;
  center: [number, number];
  zoom: number;
  photo: string;
  prose: string[];
  monuments: Monument[];
  walks: string[];
};

export type Gazette = { volume: string; part: string; date: string; topic: string };

export type WalkStop = {
  name: string;
  thai: string;
  note: string;
  lat: number;
  lon: number;
  fad?: string;
  registered?: boolean;
  gazette?: Gazette;
  locatedBy: string;
  approx?: boolean;
  approxWhy?: string;
  block?: { x: number; z: number };
  world?: string;
  tp?: string;
  /** Real OSRM leg distance/duration from the previous stop — absent on stop 1. */
  distanceFromPrevM?: number;
  durationFromPrevMin?: number;
};

export type WalkStats = {
  citedInRegister: number;
  gazetted: number;
  awaitingConsideration: number;
  walkable: number;
  oldestGazetteYear: number | null;
  newestGazetteYear: number | null;
  longestLegM: number | null;
  shortestLegM: number | null;
};

export type Walk = {
  slug: string;
  name: string;
  thai: string;
  mode: "walk" | "bike";
  pattern: string;
  areas: string[];
  intro: string;
  stops: WalkStop[];
  stats: WalkStats;
  distanceM?: number;
  durationMin?: number;
};

export type Photo = {
  slot: string;
  title: string;
  file: string;
  descriptionUrl: string;
  licence: string;
  artist: string;
};

const data = places as { areas: Area[]; walks: Walk[] };
const photos = photoManifest as Record<string, Photo>;

export const AREAS: Area[] = data.areas;
export const WALKS: Walk[] = data.walks;

export function areaBySlug(slug: string): Area | undefined {
  return AREAS.find((a) => a.slug === slug);
}

export function walkBySlug(slug: string): Walk | undefined {
  return WALKS.find((w) => w.slug === slug);
}

export function photoFor(slot: string): Photo | undefined {
  const p = photos[slot];
  // No attribution entry means no licence on record: render nothing.
  return p && p.file && p.licence ? p : undefined;
}

export function walkDistance(walk: Walk): string | null {
  if (!walk.distanceM) return null;
  return `${(walk.distanceM / 1000).toFixed(1)} km`;
}
